### ISSUE TITLE
`OrderExecuter.create_orders` should always return `orders`

### ISSUE THREAD

**Issue by thejimmylin** [finlab-python/order_executor#2]
Hi Finlab,

I'm one of your VIP users, and I really like Finlab. Thank you in advance for creating this awesome project.

I have a suggestion regarding `OrderExecutor.create_orders`. I believe it should always return `orders` regardless of whether `view_only` is set to `True` or `False`.

It would be great if it could be implemented as follows:

```python
class OrderExecutor():
    ...

    def create_orders(self, market_order=False, best_price_limit=False, view_only=False, extra_bid_pct=0):
        if [market_order, best_price_limit, bool(extra_bid_pct)].count(True) > 1:
            raise ValueError("Only one of 'market_order', 'best_price_limit', or 'extra_bid_pct' can be set.")
        if extra_bid_pct < 0 or extra_bid_pct > 0.1:
            raise ValueError("The extra_bid_pct parameter is out of the valid range 0 to 0.1")

        present_position = self.account.get_position()
        orders = (self.target_position - present_position).position

        if view_only:
            return orders

        self.cancel_orders()
        stocks = self.account.get_stocks(list({o['stock_id'] for o in orders}))

        # make orders
        for o in orders:
            # Do operations like buy/sell according to `orders`
            ...

        return orders  # <-- A new added line
```

Without this, you would have to write code like this with `OrderExecutor` because when `view_only=True`, `order_executer.create_orders` doesn't return anything:
```python
def create_my_orders(view_only):
    # Build my `position` here
    ...
    # Initialize a `order_executer` with `position` to deal with orders later
    order_executer = OrderExecutor(position, account)
    
    # If `view_only=False`, create orders.
    if view_only is False:
        order_executer.create_orders(view_only=False)
    
    # Return a reuslt dictionary
    records = order_executer.create_orders(view_only=True)
    return records
```

It seems that you create orders in one way and obtain the result in another way. It appears that you are not exactly receiving the result of the orders you are dealing with. According to the source code, you indeed are not, and it would be **even better** if you are, but I believe there would be much more to work on to achieve it.

So, with the change, it could be simply just:
```python
def create_my_orders(view_only):
    # Build my `position` here
    ...
    order_executer = OrderExecutor(position, account)
    records = order_executer.create_orders(view_only=view_only)
    return records
```

Or even this, with a bit less readability:
```python
def create_my_orders(view_only):
    # Build my `position` here
    ...
    return OrderExecutor(position, account).create_orders(view_only=view_only)
```

Since it's a small change that won't affect backward compatibility, I think it's a good idea to make the change now. When we actually implement it with the "even better" approach I mentioned earlier, we can modify it under the hood.

**Comment by koreal6803** [comment]
Thank you so much for your suggestion. I appreciate your feedback and the code snippet you provided. Please don't hesitate to reach out if you have any more ideas or questions.
